name = "bark-serverless-worker"
main = "worker/src/index.ts"
compatibility_date = "2026-06-12"

[observability]
enabled = true

[vars]
# 稳定后可以考虑关闭新设备的注册，防止他人滥用
CLOSE_REGISTER = false
# 保持默认即可，除非你知道你在干什么
APNS_TOPIC = "me.fin.bark"
APNS_KEY_ID = "LH4T9V5U4R"
APNS_TEAM_ID = "5U8LBRXG3A"
APNS_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg4vtC3g5L5HgKGJ2+T1eA0tOivREvEAY2g+juRXJkYL2gCgYIKoZIzj0DAQehRANCAASmOs3JkSyoGEWZsUGxFs/4pw1rIlSV2IC19M8u3G5kq36upOwyFWj9Gi3Ejc9d3sC7+SHRqXrEAJow8/7tRpV+-----END PRIVATE KEY-----"

[[kv_namespaces]]
binding = "DEVICE_REGISTRY"
id = "e5ea124ce7b64ac19ecdea6d21ec6d3a"
preview_id = "a47ee60cd75c4e9f902b99922ce9f791"
